import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import {getRouteData} from "@/utils/get-route-data";
import routes from "@/routes.json";
import Link from "next/link";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

function getRouteHref(route: string) {
    if (route === '/') return '/';
    return `/${route.split('.').join('/')}`
}

const RootLayout = async ({
    children, params
}: Readonly<{
    children: React.ReactNode;
    params: { path?: string[] };
}>) => {
    const routeData = await getRouteData(params.path);
    return (
        <html lang={routeData.locale}>
            <body className={inter.className}>
                <nav>
                    {Object.keys(routes).map((route) => {
                        return (
                            <Link href={route} key={route}>
                                {route}
                            </Link>
                        )
                    })}
                </nav>
                <main>
                    {children}
                </main>
            </body>
        </html>
    );
}

export default RootLayout;
